In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
a[0:3]

array([20, 21, 22])

In [4]:
a[:3]

array([20, 21, 22])

In [5]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [6]:
a[1::2]

array([21, 23, 25, 27, 29])

In [7]:
a[0::2]

array([20, 22, 24, 26, 28])

In [8]:
a[2::2]

array([22, 24, 26, 28])

In [9]:
a[0::3]

array([20, 23, 26, 29])

In [10]:
#iki boyutlu slice işlemler

In [12]:
m = np.random.randint(10,size = (5,5))

In [13]:
m

array([[4, 8, 0, 2, 2],
       [6, 5, 1, 2, 8],
       [1, 8, 9, 2, 4],
       [0, 3, 6, 3, 8],
       [3, 1, 1, 0, 8]])

In [14]:
m[:,0]

array([4, 6, 1, 0, 3])

In [15]:
m[:,1]

array([8, 5, 8, 3, 1])

In [16]:
m[:,4]

array([2, 8, 4, 8, 8])

In [17]:
m[0,:]

array([4, 8, 0, 2, 2])

In [18]:
m[0]

array([4, 8, 0, 2, 2])

In [21]:
m

array([[4, 8, 0, 2, 2],
       [6, 5, 1, 2, 8],
       [1, 8, 9, 2, 4],
       [0, 3, 6, 3, 8],
       [3, 1, 1, 0, 8]])

In [19]:
m[1,:]

array([6, 5, 1, 2, 8])

In [20]:
m[0:2,0:3]

array([[4, 8, 0],
       [6, 5, 1]])

In [22]:
m[::,:2]

array([[4, 8],
       [6, 5],
       [1, 8],
       [0, 3],
       [3, 1]])

In [23]:
m[:,0:2]

array([[4, 8],
       [6, 5],
       [1, 8],
       [0, 3],
       [3, 1]])

In [24]:
m[1:3,0:2]

array([[6, 5],
       [1, 8]])