In [2]:
import numpy as np
a = np.random.randint(10,size= 10)
a

array([5, 0, 1, 1, 8, 7, 4, 9, 0, 3])

In [3]:
a[0]

5

In [4]:
a[-1]

3

In [5]:
a[0] = 100

In [6]:
a

array([100,   0,   1,   1,   8,   7,   4,   9,   0,   3])

In [7]:
m = np.random.randint(10, size= (3,5))

In [8]:
m

array([[9, 2, 7, 4, 3],
       [4, 3, 3, 4, 3],
       [9, 4, 6, 5, 5]])

In [10]:
m[0,0]

9

In [11]:
m[1,0]

4

In [12]:
m[1,4]

3

In [13]:
m[1,4] = 99

In [14]:
m

array([[ 9,  2,  7,  4,  3],
       [ 4,  3,  3,  4, 99],
       [ 9,  4,  6,  5,  5]])

In [15]:
m[1,4] = 2.2

In [16]:
m

array([[9, 2, 7, 4, 3],
       [4, 3, 3, 4, 2],
       [9, 4, 6, 5, 5]])