In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size = (5,5))

In [3]:
a

array([[1, 9, 4, 0, 4],
       [3, 1, 4, 4, 1],
       [6, 5, 5, 1, 4],
       [2, 1, 5, 5, 8],
       [9, 4, 0, 2, 9]])

In [4]:
alt_a = a[0:3,0:2]

In [5]:
alt_a

array([[1, 9],
       [3, 1],
       [6, 5]])

In [9]:
alt_a[0,0] = 99999
alt_a[1,1] = 8888

In [10]:
alt_a

array([[99999,     9],
       [    3,  8888],
       [    6,     5]])

In [11]:
a

array([[99999,     9,     4,     0,     4],
       [    3,  8888,     4,     4,     1],
       [    6,     5,     5,     1,     4],
       [    2,     1,     5,     5,     8],
       [    9,     4,     0,     2,     9]])

In [12]:
m = np.random.randint(10, size = (5,5))
m

array([[0, 5, 4, 4, 9],
       [4, 4, 6, 1, 7],
       [6, 0, 4, 1, 8],
       [4, 0, 3, 0, 3],
       [4, 6, 9, 5, 6]])

In [13]:
alt_m = m[0:3,0:2].copy()
alt_m

array([[0, 5],
       [4, 4],
       [6, 0]])

In [14]:
alt_m[0,0] = 9999

In [15]:
alt_m

array([[9999,    5],
       [   4,    4],
       [   6,    0]])

In [16]:
m

array([[0, 5, 4, 4, 9],
       [4, 4, 6, 1, 7],
       [6, 0, 4, 1, 8],
       [4, 0, 3, 0, 3],
       [4, 6, 9, 5, 6]])