In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a = np.array ([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

In [6]:
np.array([3.14,4,2,13],dtype="int")

array([ 3,  4,  2, 13])

In [7]:
np.array([3.14,4,2,13],dtype="float32")

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

In [8]:
#sifirdan array olusturma

In [11]:
np.zeros(10, dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5), dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [16]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [17]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
np.random.normal(10,4,(3,4))

array([[ 2.75250719, 17.48022527,  6.42556229, 13.1288161 ],
       [11.75532058, 11.82413205, 11.35116352, 16.42967559],
       [ 5.55673655,  8.43162915, 13.98654847, 12.96278762]])

In [19]:
np.random.randint(0,10,(3,3))

array([[5, 5, 3],
       [8, 9, 9],
       [2, 3, 5]])

* ndim: boyut sayısı
* shape = boyut bilgisi
* size= toplam eleman sayisi
* dtype = array veri tipi

In [21]:
np.random.randint(10,size=10)

array([0, 4, 4, 0, 4, 0, 6, 4, 4, 3])

In [22]:
a = np.random.randint(10,size=10)

In [23]:
a.ndim

1

In [24]:
a.shape

(10,)

In [25]:
a.size

10

In [26]:
a.dtype

dtype('int32')

In [27]:
b = np.random.randint(10, size= (3,5))

In [28]:
b

array([[8, 0, 5, 5, 0],
       [7, 7, 6, 2, 6],
       [7, 4, 9, 6, 3]])

In [29]:
b.ndim

2

In [31]:
b.shape

(3, 5)

In [32]:
b.size

15

In [33]:
b.dtype

dtype('int32')

## Yeniden Şekillendirme (reshaping)

In [34]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a= np.arange(1,10)

In [38]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a.ndim

1

In [41]:
b = a.reshape((1,9))

In [42]:
b.ndim

2

## Array Birlestirme (Concatenation)

In [43]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [44]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [45]:
z = np.array([7,8,9])

In [46]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
#iki boyut

In [49]:
a = np.array([[1,2,3],
             [4,5,6]])

In [50]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [51]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [53]:
x = np.array([1,2,3,99,99,3,2,1])

In [54]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [55]:
a,b,c = np.split(x,[3,5])

In [56]:
a

array([1, 2, 3])

In [57]:
b

array([99, 99])

In [58]:
c

array([3, 2, 1])

In [59]:
#iki boyutlu

In [62]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [64]:
ust, alt = np.vsplit(m,[2])

In [65]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [66]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [73]:
sag, sol = np.hsplit(m, [2])

In [74]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [75]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array Sıralama (Sorting)

In [76]:
v = np.array([2,1,4,3,5])

In [77]:
v

array([2, 1, 4, 3, 5])

In [78]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [79]:
v.sort()

In [80]:
v

array([1, 2, 3, 4, 5])

In [81]:
#iki boyutlu

In [83]:
m = np.random.normal(20,5,(3,3))

In [84]:
m

array([[19.31157633, 16.1465515 , 20.19894349],
       [17.30332879, 18.93644165, 28.61560424],
       [19.05906117, 24.00082051, 18.93411342]])

In [85]:
np.sort(m, axis= 1)

array([[16.1465515 , 19.31157633, 20.19894349],
       [17.30332879, 18.93644165, 28.61560424],
       [18.93411342, 19.05906117, 24.00082051]])

In [86]:
np.sort(m, axis= 0)

array([[17.30332879, 16.1465515 , 18.93411342],
       [19.05906117, 18.93644165, 20.19894349],
       [19.31157633, 24.00082051, 28.61560424]])